### ISSUE TITLE
Ran into an issue: "Invalid zip file error - the archive is not encrypted"

### ISSUE THREAD

**Issue by hugmyndakassi** [agourlay/zip-password-finder#118]
Hi, I have a file whose contents are definitely encrypted - this much I know.

The issue happens with version:

```
$ zip-password-finder --version
zip-password-finder 0.5.1
```

which is the current version on crates.io.

`file` on Ubuntu 22.04 reports:

```
Zip archive data, at least v2.0 to extract, compression method=store
```

`unzip` as packaged with Ubuntu - version reports as 6.00 (or Ubuntu package as `6.0-26ubuntu3.1`) - reports for each of the contained files:

```
need PK compat. v5.1 (can do v4.6)
```

The file names don't seem to be encrypted.

7-Zip (pkg: `16.02+dfsg-8`) appears to be able to handle the file format, but the password is obviously deemed wrong.

Any idea what I could try, or is this simply not supported, yet? Thanks.

PS: [zipdump.py by Didier Stevens](https://blog.didierstevens.com/2023/09/05/update-zipdump-py-version-0-0-28/) also claims `ZIP file is not password protected`
PPS: _there is currently not support for zip64_ is claimed by [zip-rs](https://crates.io/crates/zip-rs) which you use, so this could already be the issue. I also noticed that the version installable via crates.io lags behind, so going to install from a local checkout ...

**Comment by agourlay** [comment]
@hugmyndakassi I have not tested `zip64` so it might be a support issue.

Thanks for adding post scriptums, the version on crates.io is indeed outdated because of https://github.com/agourlay/zip-password-finder/issues/46

BTW the underlying zip library used is https://github.com/zip-rs/zip

Try [0.7.0](https://github.com/agourlay/zip-password-finder/releases/tag/v0.7.0) and keep me posted!

**Comment by hugmyndakassi** [comment]
Hi, I apologize for the confusion. I was misled by the name `zip-rs`, you're of course right.

Version 0.7.0 has the exact same issue and the only output I can get it to produce is:

```
$ zip-password-finder -V
zip-password-finder 0.7.0
$ zip-password-finder -p ~/words.txt -i mytarget.zip
Invalid zip file error - the archive is not encrypted
```

I built the version locally, in case you think that makes a difference.

**Comment by agourlay** [comment]
Is it possible for you to share a test archive with me?

**Comment by hugmyndakassi** [comment]
> Is it possible for you to share a test archive with me?

Afraid in this case it's not possible for the original file. But you gave me an idea to try and mimic the original file with a known password to see how to get the same flags in each respective record. If this succeeds, I'll share it here.

**Comment by hugmyndakassi** [comment]
Just FYI, using a different template in 010 Editor, I was able to get more detailed info in regard to the storage and encryption method.

File record:
![image](https://github.com/agourlay/zip-password-finder/assets/79632072/4c0a58be-1b07-4229-8da0-708ab7454974)

Directory entry:
![image](https://github.com/agourlay/zip-password-finder/assets/79632072/d889723c-4a0d-4540-a250-0c17cbddcbb4)

**Comment by hugmyndakassi** [comment]
@agourlay just wondering, are you aware of any tools that purport to crack ZIP passwords _and_ allow you to select a given member (e.g. by path) and provide a plain text version for that?

So, suppose I am looking at an archive which is password-protected, but I am in possession of some of the files contained. Is there a way to aid the cracking process (mainly speed it up) by providing the plain text version for a given member?

**Comment by agourlay** [comment]
Maybe have a look at [bkcrack](https://github.com/kimci86/bkcrack) and check if it could be somehow applied to your use case.

What is the state of your issue with `zip-password-finder`?

**Comment by RangoZhao** [comment]
You can try add '--fileNumber 1' into the command.  
May be the first file is directory. It is not encrypted.

**Comment by agourlay** [comment]
FYI you could try the new [0.8.0](https://github.com/agourlay/zip-password-finder/releases/tag/v0.8.0) release.

Not only it uses an improved zip crate but I also improved the error messages for your case.

**Comment by hugmyndakassi** [comment]
Only just saw it now. I'll give it a go and report back. Thank you!

**Comment by agourlay** [comment]
@hugmyndakassi anything new to report? :)

**Comment by agourlay** [comment]
[0.8.1](https://github.com/agourlay/zip-password-finder/releases/tag/v0.8.1) is out with various internal improvements

**Comment by hugmyndakassi** [comment]
I'm sorry, I totally lost sight of this.

**Comment by hugmyndakassi** [comment]
I'm so sorry. Completely lost sight of this matter,

```
Invalid zip file error - the selected file in the archive is not encrypted (file_number:0 file_name:directory_name/)
```

was the first thing I saw. Then I had to find something that wasn't a directory. Presumably there could be a heuristic that ensures that the ZIP file entry is a file or directory, skipping directories automatically.

And then it seemingly worked:

```
$ zip-password-finder --fileNumber 3 --inputFile ./some_zip_file.zip
Archive encrypted with AES256 - expect a long wait time
Starting 4 workers to test passwords
Generating passwords with length from 1 to 10 for charset with length 62
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
Starting search space for password length 1 (62 possibilities)
Starting search space for password length 2 (3844 possibilities) (62 passwords generated so far)
Starting search space for password length 3 (238328 possibilities) (3906 passwords generated so far)
Starting search space for password length 4 (14776336 possibilities) (242234 passwords generated so far)
Password found: ....
```

Alas, the "found" four character password did not actually work when attempting to unpack the file with 7-Zip.

**Comment by agourlay** [comment]
Thanks for coming back ;)

I agree that the file selection is not idea here, there is room for improvement.

Regarding the wrong password there is already a very similar report https://github.com/agourlay/zip-password-finder/issues/185

I wonder what is special about those archives.

**Comment by agourlay** [comment]
Please try [0.9.1](https://github.com/agourlay/zip-password-finder/releases/tag/v0.9.1) which contains a fix for this kind of false positives.

**Comment by hugmyndakassi** [comment]
> Please try [0.9.1](https://github.com/agourlay/zip-password-finder/releases/tag/v0.9.1) which contains a fix for this kind of false positives.

Hi, this issue seems to be resolved with 0.9.1! However, for now I had to give up after seven hours of runtime:

```
$ zip-password-finder --fileNumber 3 --inputFile ./some_zip_file.zip
Archive encrypted with AES256 - expect a long wait time
Starting 4 workers to test passwords
Generating passwords with length from 1 to 10 for charset with length 62
0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
Starting search space for password length 1 (62 possibilities)
Starting search space for password length 2 (3844 possibilities) (62 passwords generated so far)
Starting search space for password length 3 (238328 possibilities) (3906 passwords generated so far)
Starting search space for password length 4 (14776336 possibilities) (242234 passwords generated so far)
Starting search space for password length 5 (916132832 possibilities) (15018570 passwords generated so far)
[07:00:30] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 121016000/853058371866181866 throughput:4,608.4044/s (eta:5869776y)
```

**Comment by agourlay** [comment]
Happy to hear the "problems" are solved!

Sorry about compute cost, there not much I can do right now.
Can you maybe reduce the charset? Start with larger min password len?

Otherwise can we close this issue?

**Comment by hugmyndakassi** [comment]
> Otherwise can we close this issue?

I think so. Thanks! In fact since I already have the button right below this text box, let me do it.
