### ISSUE TITLE
Small flaw in calculation of possibilities

### ISSUE THREAD

**Issue by filipeestima** [agourlay/zip-password-finder#181]
When you select --minPasswordLen bigger than 1, the first line "Starting search space for password length X (XX possibilities)" doesn't correspond to the actual number of possibilities, but to the number of charset (as if --minPasswordLen was set to 1).

Example:

Using --minPasswordLen 1 (default) with charset d will show "Starting search space for password length 1 (10 possibilities)"
Using --minPasswordLen 3 with charset d will show "Starting search space for password length 3 (10 possibilities)" instead of 1000 possibilities.

**Comment by agourlay** [comment]
fixed in [0.9.1](https://github.com/agourlay/zip-password-finder/releases/tag/v0.9.1)
