### ISSUE TITLE
Suggestion 2: Display total time elapsed when job is finished.

### ISSUE THREAD

**Issue by filipeestima** [agourlay/zip-password-finder#183]
When password is found (or not found), display total time elapsed and average passwords per second (these informations are only shown during processing). I think it can be useful to know how much time the machine has devoted to a task, specially when we leave it alone.

**Comment by agourlay** [comment]
I have added the full time in [0.9.1](https://github.com/agourlay/zip-password-finder/releases/tag/v0.9.1)
The average password per seconds requires a bit more work.
Please open a new issue if you really want it :)
