### ISSUE TITLE
Any way to find the password for items inside a folder?

### ISSUE THREAD

**Issue by skewbug** [agourlay/zip-password-finder#196]
For example, the first folder in the hierarchy inside the zip is not encrypted, but all the files inside that folder are. 
<img src="https://github.com/user-attachments/assets/43818dc4-ab47-4909-a996-bdd4327715d6" width="50%"/>
<img src="https://github.com/user-attachments/assets/664d52b3-4dc9-412a-8f50-4cb1c4d0f074" width="50%"/>
Pointing the tool to the zip as a whole provides this error:
![image](https://github.com/user-attachments/assets/60623745-c90d-464c-9001-1d24d6838fae)
Is there any way to point it to a file path _inside_ the zip? If not, please consider this a feature request.

**Comment by agourlay** [comment]
You can pass a file number within the archive to focus on with `--fileNumber`

**Comment by skewbug** [comment]
I see; I didn't realize that it counted toward files inside folders. For future reference, is there a way to check the file number in situations where the folder hierarchy is more complex?

**Comment by filipeestima** [comment]
> I see; I didn't realize that it counted toward files inside folders. For future reference, is there a way to check the file number in situations where the folder hierarchy is more complex?

That's an interesting question. Arnaud, it would be nice to have this information on the instructions page. Some ZIP files have lots of folders inside folders. Perhaps the program can show information "Working on folder1\folder2\folder3\filex.jpg" so the user can be sure that the correct --fileNumber parameter was used.

**Comment by agourlay** [comment]
Thanks for suggestion regarding printing information about the targeted file :+1: 

I implemented it quickly in [0.9.2](https://github.com/agourlay/zip-password-finder/releases/tag/v0.9.2) so you can experiment with it.

Hopefully it makes things less confusing.

**Comment by agourlay** [comment]
Any feedback on the release?
Can this issue be close?

**Comment by filipeestima** [comment]
I didn't find old or new issues with the latest build. With info regarding the targeted file, it became easier to be sure which file's encryption it's trying to break.
