### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by orhun** [agourlay/zip-password-finder#40]
Hey!

Have you considered publishing `zip-password-finder` on [crates.io](https://crates.io/)? I think it would be nice to install via `cargo install zip-password-finder`.

I can submit a PR to update the release workflow if you find this applicable. LMK! 🐻

**Comment by agourlay** [comment]
I don't usually use cargo to install non cargo related CLIs but we can give it a try if you think it makes sense :+1:

**Comment by agourlay** [comment]
Here it is https://crates.io/crates/zip-password-finder

Thanks!

**Comment by agourlay** [comment]
FYI the publish process to crates.io is currently broken https://github.com/agourlay/zip-password-finder/issues/46
